# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '360play clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 360play clone


pod "iOSDropDown"

  target '360play cloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '360play cloneUITests' do
    # Pods for testing
  end

end
